### ISSUE TITLE
Unitframe debuff timers range

### ISSUE THREAD

**Issue by kev41** [zetone/enemyFrames#2]
As a hunter my spells are 35 yards, but the timer on uniteframe only appears I believe at less than 30 yards.

Can I  change it somewhere so it shows the timer if I am at my maxrange (35yards).

Amazing addon!
Thanks in advance,
Kev

**Comment by Schaka** [comment]
There's a /console command that makes your combatlog range higher (up to 100y). YOu can find it on Kronos forums somewhere.

**Comment by kev41** [comment]
@Schaka 
Thank you, that was the problem. I didn't find it on Kronos but I used google.
